### ISSUE TITLE
Does not work with ipywidgets 7.4.0 and altair 2.2.2

### ISSUE THREAD

**Issue by chmduquesne** [altair-viz/altair_widgets#12]
When running

    interact_with(iris)

I get the following output

    TypeError                                 Traceback (most recent call last)
    <ipython-input-1-1ad553e9f0bc> in <module>()
          8 
          9 from altair_widgets import interact_with
    ---> 10 interact_with(iris)
    
    ~/code/perso/notebooks/data-science-exercises/venv/lib/python3.7/site-packages/altair_widgets/widget.py in interact_with(df, ndims, **kwargs)
         26 
         27     """
    ---> 28     return Interact(df, ndims=ndims, **kwargs)
         29 
         30 
    
    ~/code/perso/notebooks/data-science-exercises/venv/lib/python3.7/site-packages/altair_widgets/widget.py in __init__(self, df, ndims, show)
         56             display(self.controller)
         57 
    ---> 58         self.plot(show=show)
         59 
         60     def _show_advanced(self, button, disable=1):
    
    ~/code/perso/notebooks/data-science-exercises/venv/lib/python3.7/site-packages/altair_widgets/widget.py in plot(self, show)
        168         mark = mark_opts.pop('mark')
        169         Chart_mark = getattr(altair.Chart(self.df), mark)
    --> 170         self.chart = Chart_mark(**mark_opts).encode(**kwargs)
        171         if show and self.show:
        172             clear_output()
    
    ~/code/perso/notebooks/data-science-exercises/venv/lib/python3.7/site-packages/altair/vegalite/v2/api.py in encode(self, *args, **kwargs)
       1238                 if condition is not Undefined:
       1239                     obj['condition'] = _wrap_in_channel_class(condition, prop)
    -> 1240             kwargs[prop] = _wrap_in_channel_class(obj, prop)
       1241 
       1242 
    
    ~/code/perso/notebooks/data-science-exercises/venv/lib/python3.7/site-packages/altair/vegalite/v2/api.py in _wrap_in_channel_class(obj, prop)
       1214                 return [_wrap_in_channel_class(subobj, prop) for subobj in obj]
       1215 
    -> 1216             if 'value' in obj:
       1217                 clsname += 'Value'
       1218 
    
    TypeError: argument of type 'NoneType' is not iterable
    
If I then click on the button "Options", I get additional errors:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    ~/code/perso/notebooks/data-science-exercises/venv/lib/python3.7/site-packages/altair_widgets/widget.py in _show_advanced(self, button, disable)
         84             c.observe(self._update, names='value')
         85 
    ---> 86         visible = self.controller.children[row].children[-1].visible
         87         self.controller.children[row].children[disable].disabled = not visible
         88         self.controller.children[row].children[-1].visible = not visible
    
    AttributeError: 'VBox' object has no attribute 'visible'

**Comment by jakevdp** [comment]
I don't think this repo has been updated to work with Altair 2.0

**Comment by chmduquesne** [comment]
I see... Any plans to update it?

**Comment by stsievert** [comment]
Hopefully. I’ll try to find some time for this. One of the other options is voyager, https://github.com/altair-viz/jupyterlab_voyager/

**Comment by eyaltra** [comment]
with what version it does work?

**Comment by jakevdp** [comment]
It works with Altair versions 1.X, I believe.

**Comment by stsievert** [comment]
Closed by #17
